site_name: RxPipes
theme:
  name: material
  features:
    - navigation.instant
    - nagivation.tabs
    - navigation.sections
    - navigation.expand
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: "google"
          rendering:
            show_root_heading: no
            show_category_heading: no
extra_css:
  - css/mkdocstrings.css
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
  - Reference:
      rxpipes:
        - pipeline.py: rxpipes/pipeline.md
        - concurrency.py: rxpipes/concurrency.md
  - Examples:
    - Reactive: examples/reactive.md
    - Concurrency: examples/concurrency.md
    - Image Processing: examples/image-processing.md
