version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps0-{{ .Branch }}-{{ checksum "setup.py"  }}
      - run:
          command: pip install .[test]
          name: Install
      - save_cache:
          key: deps0-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - /home/circleci/.local/lib/
      - run:
          command: pytest tests
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
